"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const task_controller_1 = require("../controllers/task.controller");
const router = (0, express_1.Router)();
router.route("/addTask").post(auth_middleware_1.verifyJWT, task_controller_1.addTask);
router.route("/getTasks").get(auth_middleware_1.verifyJWT, task_controller_1.getTasks);
router.route("/updateTask").put(auth_middleware_1.verifyJWT, task_controller_1.updateTask);
router.route("/deleteTask").delete(auth_middleware_1.verifyJWT, task_controller_1.deleteTask);
exports.default = router;
